### ISSUE TITLE
Filter out solution folders when iterating projects

### ISSUE THREAD

**Issue by luisgoncalves** [Ashthos/Cake.StyleCop#2]
Version 0.15 of Cake introduced support for solution folders on `SolutionParser`. This broke `Cake.StyleCop` because additional items are now [returned on the `Projects` collection](https://github.com/Ashthos/Cake.StyleCop/blob/master/Cake.Stylecop/StyleCopRunner.cs#L59) and those items don't have a corresponding `.csproj` file on disk.

We need to filter out the "projects" that are actually solution fodlers.I see two options to handle this:
1. Hard-code the well-known magic string for the `Type` of solution folders. This keeps the dependency on Cake in the same version.
2. Assume the minimum version of Cake to 0.15.0 and filter out either using the [`SolutionFolder` class](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Solution/SolutionParser.cs#L79) or the `SolutionFolder.TypeIdentifier` constant.

Since Cake still [doesn't have a way of matching addin versions to Cake versions](https://github.com/cake-build/cake/issues/1240), option 2 may break some scenarios. But everything is still on v 0.XX.X.

Which would you prefer?

**Comment by Symbianx** [comment]
I've created a pull request where I've taken the first approach to fix it for folder project types. 
There may be some projects that will break the addin as well, but I'm not confortable enough with the .sln format to know.

**Comment by Symbianx** [comment]
@Ashthos any word on this?

**Comment by vip32** [comment]
i can confirm that solution folders are causing problems with the stylecop addin. please include @Symbianx his PR

**Comment by luis-goncalves-bold** [comment]
Any news on this?

**Comment by luisgoncalves** [comment]
Any news on this?

**Comment by Symbianx** [comment]
@luisgoncalves, this issue has been fixed with the merge of PR #3.
